//magical places generator page 22
let namType = ["garden","tree","forest","woods","grove","field","plains","mesa/plateau","bridge","circle","gate","shrine","spire (rock)","valley","trench","knoll/hill","rock","mount","peak","dome","cave","cavern","grotto","well","pond","lake","lagoon","falls","river","brook/stream"];
let namName = ["crystal ","divine ","enchanted ","faraway ","golden ","heavenly ","living ","magical ","paradise ","singing ","sorcerer's ","wishing ","wizard's "," of accord"," of awakening"," of dreams"," of enlightenment"," of healing"," of honor"," of joy"," of life"," of light"," of peace"," of power"," of serenity"," of souls"," of the ancients"," of tranquility"," of understanding"," of visions"];
let boon = ["all magic-user spells (including sub-types) memorized at location will have double effect when cast","all cleric spells (including sub-types) memorized at location will have double effect when cast","5-20 pixies dwell nearby; will normally remain invisible and cause mischief to characters visiting location","all visitors must save vs. magic or be sent on quest which will send them 'faraway' to retrieve an obscure object and return","removes curses from any cursed character who visits location","all lawful/good clerics who pray here receive a +1 'to hit' bonus; duration is # of days = # hours spent praying (no bonus for druids)","provides visitors +1 protection from undead; duration = 1 day for each 2 days spent at location","all magic weapons (not including rods/staves/wands) and armor receive +1 bonus; duration = 1 day for each 2 days spent at location","removes curses from any cursed character","magical singing; all characters who hear singing must save vs. magic or never want to leave the location","any magic-user spells memorized here has a 50% chance of not being forgotten the first time it is cast (will be forgotten after 2nd casting)","1 in 30 chance a wish (as spell) made in presence of location will come true; once attempt per character, regardless of # of visits","allows magic-user in presence of place to memorize up to twice the normal amount of spells normally allowed (if time allows as normal)","all chaotic/evil characters become neutral in presence of location","doubles the normal time limit on deceased corpses when raise dead spell is cast in this location","prophetic visions during sleep while near place; strength/clarity of visions based on proximity to place","3 days of continual meditation, prayer and fasting will raise a wisdom by +1 (one time only bonus)","restores HPs (duration time at location vs. restored points at DM discretion); also cures poison","all lawful/good fighters who rest here receive a +1 'to hit' bonus; duration of bonus = duration of stay at location","removes the effects of any magical fear","provides regenerative power to visitors; +1 HP per day; duration of ability = 1 day for each 2 days spent at location","provides visitors +1 protection from evil; duration = 1 day for each 3 days spent at location","removes effects of confusion and/or fear","every spell memorized at location will have double effect when cast","cures lycanthropy to afflicted who visit location","halves the normal time required to recuperate (while at location) for a cleric who has cast a resurrection spell","all demi-human who rest here receive a +1 'to hit' bonus; duration = 1 day for each 2 days spent at location","cures disease to afflicted who visit location","all thieves (and thief types) who rest here receive a +1 level bonus to thieving skills; duration = 1 day for each 3 days spent at location","site is disguised by hallucinatory terrain; save vs. magic or believe illusion"];
$("#magRoll").click(function () {
    let roll1 = rollDie(0,29);
    let roll2 = rollDie(0,29);
    let namer1 = namType[roll1];
    let namer2 = namName[roll2];
    let theName;
    if (roll2 < 13) {
        theName = namer2 + namer1;
    } else {
        theName = namer1 + namer2;
    }
    document.getElementById("namRslt").innerHTML = theName;
    document.getElementById("boonRslt").innerHTML = boon[roll2];
});